export const actionTypes = {
    THONG_TIN_KHACH_HANG: 'THONG_TIN_KHACH_HANG',
    LOAD_KHACH_HANG: 'LOAD_KHACH_HANG',
    XOA_KHACH_HANG: 'XOA_KHACH_HANG',
    CAP_NHAT_KHACH_HANG: 'CAP_NHAT_KHACH_HANG',
}